# Generated by Django 2.2.7 on 2019-11-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('working_state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkerCoordinate',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
            ],
        ),
    ]
