# Generated by Django 2.2.7 on 2019-11-16 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fan_sensor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sensor',
        ),
        migrations.DeleteModel(
            name='WorkerCoordinate',
        ),
    ]
